import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { BillInfoFormData } from "@/lib/schemas/billInfo.schema";

export const billInfoFormFields: FieldConfig<BillInfoFormData>[] = [
  {
    name: "memId",
    label: "Member",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/members",
      labelField: "memName",
      valueField: "_id",
      searchable: true,
      filter: (item: Record<string, unknown>) => !item.isDeleted,
    },
    placeholder: "Select member",
  },
  {
    name: "fileId",
    label: "File",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/file",
      labelField: "fileRegNo",
      valueField: "_id",
      searchable: true,
      filter: (item: Record<string, unknown>) => !item.isDeleted,
    },
    placeholder: "Select file",
  },
  {
    name: "billTypeId",
    label: "Bill Type",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/billtype/dropdown",
      labelField: "label",
      valueField: "value",
      searchable: false,
      filter: () => true,
    },
    placeholder: "Select bill type",
  },
  {
    name: "billMonth",
    label: "Bill Month",
    type: "text",
    required: true,
    placeholder: "e.g., January 2026",
  },
  {
    name: "billAmount",
    label: "Bill Amount",
    type: "number",
    required: true,
    min: 0,
    step: 0.01,
    placeholder: "0",
  },
  {
    name: "fineAmount",
    label: "Fine Amount",
    type: "number",
    min: 0,
    step: 0.01,
    placeholder: "0",
  },
  {
    name: "arrears",
    label: "Arrears",
    type: "number",
    min: 0,
    step: 0.01,
    placeholder: "0",
  },
  {
    name: "dueDate",
    label: "Due Date",
    type: "date",
    required: true,
    placeholder: "Select due date",
  },
  {
    name: "gracePeriodDays",
    label: "Grace Period (Days)",
    type: "number",
    min: 0,
    max: 30,
    placeholder: "7",
  },
  {
    name: "notes",
    label: "Remarks",
    type: "textarea",
    rows: 3,
    placeholder: "Optional remarks...",
  },
];
