// src/lib/constants/installmentForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { InstallmentFormData } from "@/lib/schemas/installment.schema";

export const installmentFormFields: FieldConfig<InstallmentFormData>[] = [
  {
    name: "fileId",
    label: "File",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/file",
      labelField: "fileRegNo",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select file",
  },
  {
    name: "memId",
    label: "Member",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/members",
      labelField: "memName",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select member",
  },
  {
    name: "plotId",
    label: "Plot",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/plots",
      labelField: "plotNo",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select plot",
  },
  {
    name: "installmentCategoryId",
    label: "Installment Category",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/installmentcategory",
      labelField: "instCatName",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select installment category",
  },
  {
    name: "installmentNo",
    label: "Installment Number",
    type: "number",
    required: true,
    placeholder: "Enter installment number",
    min: 1,
    step: 1,
  },
  {
    name: "installmentTitle",
    label: "Installment Title",
    type: "text",
    required: true,
    placeholder: "Enter installment title",
  },
  {
    name: "installmentType",
    label: "Installment Type",
    type: "select",
    required: true,
    options: [
      { label: "Monthly", value: "Monthly" },
      { label: "Quarterly", value: "Quarterly" },
      { label: "Half-Yearly", value: "Half-Yearly" },
      { label: "Yearly", value: "Yearly" },
      { label: "Balloon", value: "Balloon" },
      { label: "Down Payment", value: "Down Payment" },
      { label: "Possession Fee", value: "Possession Fee" },
      { label: "Balloting Fee", value: "Balloting Fee" },
      { label: "Utility Charges", value: "Utility Charges" },
      { label: "Development Charges", value: "Development Charges" },
      { label: "Legal Fee", value: "Legal Fee" },
      { label: "Transfer Fee", value: "Transfer Fee" },
      { label: "Other", value: "Other" },
    ],
    defaultValue: "Monthly",
  },
  {
    name: "dueDate",
    label: "Due Date",
    type: "date",
    required: true,
    min: new Date(),
  },
  {
    name: "amountDue",
    label: "Amount Due",
    type: "number",
    required: true,
    placeholder: "Enter amount due",
    min: 0,
    step: 0.01,
  },
  {
    name: "lateFeeSurcharge",
    label: "Late Fee Surcharge",
    type: "number",
    required: false,
    placeholder: "Enter late fee surcharge",
    min: 0,
    step: 0.01,
  },
  {
    name: "installmentRemarks",
    label: "Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter any remarks",
    rows: 3,
  },
];

export const bulkInstallmentFormFields: FieldConfig<any>[] = [
  {
    name: "fileId",
    label: "File",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/file",
      labelField: "fileRegNo",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select file",
  },
  {
    name: "memId",
    label: "Member",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/members",
      labelField: "memName",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select member",
  },
  {
    name: "plotId",
    label: "Plot",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/plots",
      labelField: "plotNo",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select plot",
  },
  {
    name: "installmentCategoryId",
    label: "Installment Category",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/installmentcategory",
      labelField: "instCatName",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select installment category",
  },
  {
    name: "installmentType",
    label: "Installment Type",
    type: "select",
    required: true,
    options: [
      { label: "Monthly", value: "Monthly" },
      { label: "Quarterly", value: "Quarterly" },
      { label: "Half-Yearly", value: "Half-Yearly" },
      { label: "Yearly", value: "Yearly" },
      { label: "Balloon", value: "Balloon" },
    ],
    defaultValue: "Monthly",
  },
  {
    name: "totalInstallments",
    label: "Total Installments",
    type: "number",
    required: true,
    placeholder: "Enter total number of installments",
    min: 1,
    max: 360,
    step: 1,
  },
  {
    name: "amountPerInstallment",
    label: "Amount Per Installment",
    type: "number",
    required: true,
    placeholder: "Enter amount per installment",
    min: 0,
    step: 0.01,
  },
  {
    name: "startDate",
    label: "Start Date",
    type: "date",
    required: true,
    min: new Date(),
  },
  {
    name: "frequency",
    label: "Payment Frequency",
    type: "select",
    required: true,
    options: [
      { label: "Monthly", value: "monthly" },
      { label: "Quarterly", value: "quarterly" },
      { label: "Half-Yearly", value: "half-yearly" },
      { label: "Yearly", value: "yearly" },
    ],
    defaultValue: "monthly",
  },
  {
    name: "installmentTitle",
    label: "Installment Title",
    type: "text",
    required: false,
    placeholder: "Optional: Enter installment title pattern",
  },
];

export const paymentFormFields: FieldConfig<any>[] = [
  {
    name: "amountPaid",
    label: "Payment Amount",
    type: "number",
    required: true,
    placeholder: "Enter payment amount",
    min: 0.01,
    step: 0.01,
  },
  {
    name: "paidDate",
    label: "Payment Date",
    type: "date",
    required: true,
    max: new Date(),
  },
  {
    name: "paymentMode",
    label: "Payment Mode",
    type: "select",
    required: true,
    options: [
      { label: "Cash", value: "Cash" },
      { label: "Bank Transfer", value: "Bank Transfer" },
      { label: "Cheque", value: "Cheque" },
      { label: "Online Payment", value: "Online Payment" },
      { label: "Credit Card", value: "Credit Card" },
      { label: "Debit Card", value: "Debit Card" },
      { label: "Mobile Wallet", value: "Mobile Wallet" },
    ],
    defaultValue: "Cash",
  },
  {
    name: "transactionRefNo",
    label: "Transaction Reference",
    type: "text",
    required: false,
    placeholder: "Enter transaction reference number",
  },
  {
    name: "remarks",
    label: "Payment Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter any payment remarks",
    rows: 2,
  },
];

export const updateInstallmentFormFields: FieldConfig<any>[] = [
  {
    name: "installmentNo",
    label: "Installment Number",
    type: "number",
    required: false,
    placeholder: "Enter installment number",
    min: 1,
    step: 1,
  },
  {
    name: "installmentTitle",
    label: "Installment Title",
    type: "text",
    required: false,
    placeholder: "Enter installment title",
  },
  {
    name: "installmentType",
    label: "Installment Type",
    type: "select",
    required: false,
    options: [
      { label: "Monthly", value: "Monthly" },
      { label: "Quarterly", value: "Quarterly" },
      { label: "Half-Yearly", value: "Half-Yearly" },
      { label: "Yearly", value: "Yearly" },
      { label: "Balloon", value: "Balloon" },
      { label: "Down Payment", value: "Down Payment" },
      { label: "Possession Fee", value: "Possession Fee" },
      { label: "Balloting Fee", value: "Balloting Fee" },
      { label: "Utility Charges", value: "Utility Charges" },
      { label: "Development Charges", value: "Development Charges" },
      { label: "Legal Fee", value: "Legal Fee" },
      { label: "Transfer Fee", value: "Transfer Fee" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    name: "dueDate",
    label: "Due Date",
    type: "date",
    required: false,
  },
  {
    name: "amountDue",
    label: "Amount Due",
    type: "number",
    required: false,
    placeholder: "Enter amount due",
    min: 0,
    step: 0.01,
  },
  {
    name: "lateFeeSurcharge",
    label: "Late Fee Surcharge",
    type: "number",
    required: false,
    placeholder: "Enter late fee surcharge",
    min: 0,
    step: 0.01,
  },
  {
    name: "amountPaid",
    label: "Amount Paid",
    type: "number",
    required: false,
    placeholder: "Enter amount paid",
    min: 0,
    step: 0.01,
  },
  {
    name: "paidDate",
    label: "Paid Date",
    type: "date",
    required: false,
    max: new Date(),
  },
  {
    name: "paymentMode",
    label: "Payment Mode",
    type: "select",
    required: false,
    options: [
      { label: "Cash", value: "Cash" },
      { label: "Bank Transfer", value: "Bank Transfer" },
      { label: "Cheque", value: "Cheque" },
      { label: "Online Payment", value: "Online Payment" },
      { label: "Credit Card", value: "Credit Card" },
      { label: "Debit Card", value: "Debit Card" },
      { label: "Mobile Wallet", value: "Mobile Wallet" },
    ],
  },
  {
    name: "transactionRefNo",
    label: "Transaction Reference",
    type: "text",
    required: false,
    placeholder: "Enter transaction reference number",
  },
  {
    name: "status",
    label: "Status",
    type: "select",
    required: false,
    options: [
      { label: "Unpaid", value: "Unpaid" },
      { label: "Partially Paid", value: "Partially Paid" },
      { label: "Paid", value: "Paid" },
      { label: "Overdue", value: "Overdue" },
      { label: "Cancelled", value: "Cancelled" },
      { label: "Refunded", value: "Refunded" },
    ],
  },
  {
    name: "installmentRemarks",
    label: "Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter any remarks",
    rows: 3,
  },
];
