// src/lib/constants/nomineeForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { NomineeFormData } from "@/lib/schemas/nominee.schema";

export const nomineeFormFields: FieldConfig<NomineeFormData>[] = [
  {
    name: "memId",
    label: "Member",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/members",
      labelField: "memName",
      valueField: "_id",
      searchable: true,
    },
    placeholder: "Select member",
  },
  {
    name: "nomineeName",
    label: "Nominee Name",
    type: "text",
    required: true,
    placeholder: "Enter nominee name",
  },
  {
    name: "nomineeCNIC",
    label: "Nominee CNIC",
    type: "text",
    required: true,
    placeholder: "XXXXX-XXXXXXX-X",
    mask: "99999-9999999-9",
  },
  {
    name: "relationWithMember",
    label: "Relation with Member",
    type: "select",
    required: true,
    options: [
      { label: "Son", value: "Son" },
      { label: "Daughter", value: "Daughter" },
      { label: "Wife", value: "Wife" },
      { label: "Husband", value: "Husband" },
      { label: "Father", value: "Father" },
      { label: "Mother", value: "Mother" },
      { label: "Brother", value: "Brother" },
      { label: "Sister", value: "Sister" },
      { label: "Uncle", value: "Uncle" },
      { label: "Aunt", value: "Aunt" },
      { label: "Grandfather", value: "Grandfather" },
      { label: "Grandmother", value: "Grandmother" },
      { label: "Other", value: "Other" },
    ],
    defaultValue: "Son",
  },
  {
    name: "nomineeContact",
    label: "Contact Number",
    type: "text",
    required: true,
    placeholder: "03XXXXXXXXX",
    mask: "99999999999",
  },
  {
    name: "nomineeEmail",
    label: "Email Address",
    type: "email",
    required: false,
    placeholder: "nominee@example.com",
  },
  {
    name: "nomineeAddress",
    label: "Address",
    type: "textarea",
    required: false,
    placeholder: "Enter nominee address",
    rows: 2,
  },
  {
    name: "nomineeSharePercentage",
    label: "Share Percentage",
    type: "number",
    required: false,
    placeholder: "Enter share percentage",
    min: 0,
    max: 100,
    step: 0.01,
    defaultValue: 100,
  },
];

export const updateNomineeFormFields: FieldConfig<any>[] = [
  {
    name: "nomineeName",
    label: "Nominee Name",
    type: "text",
    required: false,
    placeholder: "Enter nominee name",
  },
  {
    name: "nomineeCNIC",
    label: "Nominee CNIC",
    type: "text",
    required: false,
    placeholder: "XXXXX-XXXXXXX-X",
    mask: "99999-9999999-9",
  },
  {
    name: "relationWithMember",
    label: "Relation with Member",
    type: "select",
    required: false,
    options: [
      { label: "Son", value: "Son" },
      { label: "Daughter", value: "Daughter" },
      { label: "Wife", value: "Wife" },
      { label: "Husband", value: "Husband" },
      { label: "Father", value: "Father" },
      { label: "Mother", value: "Mother" },
      { label: "Brother", value: "Brother" },
      { label: "Sister", value: "Sister" },
      { label: "Uncle", value: "Uncle" },
      { label: "Aunt", value: "Aunt" },
      { label: "Grandfather", value: "Grandfather" },
      { label: "Grandmother", value: "Grandmother" },
      { label: "Other", value: "Other" },
    ],
  },
  {
    name: "nomineeContact",
    label: "Contact Number",
    type: "text",
    required: false,
    placeholder: "03XXXXXXXXX",
    mask: "99999999999",
  },
  {
    name: "nomineeEmail",
    label: "Email Address",
    type: "email",
    required: false,
    placeholder: "nominee@example.com",
  },
  {
    name: "nomineeAddress",
    label: "Address",
    type: "textarea",
    required: false,
    placeholder: "Enter nominee address",
    rows: 2,
  },
  {
    name: "nomineeSharePercentage",
    label: "Share Percentage",
    type: "number",
    required: false,
    placeholder: "Enter share percentage",
    min: 0,
    max: 100,
    step: 0.01,
  },
  {
    name: "isActive",
    label: "Active Status",
    type: "switch",
    required: false,
    defaultValue: true,
  },
];
