// src/lib/constants/plotForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { PlotFormData } from "@/lib/schemas/plot.schema";

export const plotFormFields: FieldConfig<PlotFormData>[] = [
  {
    name: "projectId",
    label: "Project",
    type: "relationship",
    required: true,
    placeholder: "Select project",
    relationship: {
      endpoint: "/projects",
      labelField: "projName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotNo",
    label: "Plot Number",
    type: "text",
    required: true,
    placeholder: "Enter plot number",
  },
  {
    name: "plotBlockId",
    label: "Plot Block",
    type: "relationship",
    required: true,
    placeholder: "Select plot block",
    relationship: {
      endpoint: "/plotblocks",
      labelField: "plotBlockName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotSizeId",
    label: "Plot Size",
    type: "relationship",
    required: true,
    placeholder: "Select plot size",
    relationship: {
      endpoint: "/plotsizes",
      labelField: "plotSizeName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotType",
    label: "Plot Type",
    type: "select",
    required: true,
    options: [
      { label: "Residential", value: "residential" },
      { label: "Commercial", value: "commercial" },
      { label: "Industrial", value: "industrial" },
      { label: "Agricultural", value: "agricultural" },
      { label: "Corner", value: "corner" },
      { label: "Park Facing", value: "park_facing" },
      { label: "Main Boulevard", value: "main_boulevard" },
      { label: "Standard", value: "standard" },
    ],
    placeholder: "Select plot type",
  },
  {
    name: "plotCategoryId",
    label: "Plot Category",
    type: "relationship",
    required: true,
    placeholder: "Select plot category",
    relationship: {
      endpoint: "/plotcategories",
      labelField: "categoryName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotStreet",
    label: "Street",
    type: "text",
    required: false,
    placeholder: "Enter street name",
  },
  {
    name: "plotLength",
    label: "Length",
    type: "number",
    required: true,
    placeholder: "Enter length",
    step: 0.01,
    min: 0.01,
  },
  {
    name: "plotWidth",
    label: "Width",
    type: "number",
    required: true,
    placeholder: "Enter width",
    step: 0.01,
    min: 0.01,
  },
  {
    name: "plotAreaUnit",
    label: "Area Unit",
    type: "select",
    required: true,
    options: [
      { label: "Square Feet", value: "sqft" },
      { label: "Square Meters", value: "sqm" },
      { label: "Marla", value: "marla" },
      { label: "Kanal", value: "kanal" },
      { label: "Acre", value: "acre" },
    ],
    placeholder: "Select area unit",
    defaultValue: "sqft",
  },
  {
    name: "salesStatusId",
    label: "Sales Status",
    type: "relationship",
    required: true,
    placeholder: "Select sales status",
    relationship: {
      endpoint: "/sales-status",
      labelField: "statusName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "srDevStatId",
    label: "Development Status",
    type: "relationship",
    required: false,
    placeholder: "Select development status",
    relationship: {
      endpoint: "/sr-dev-status",
      labelField: "srDevStatName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotBasePrice",
    label: "Base Price",
    type: "number",
    required: true,
    placeholder: "Enter base price",
    step: 0.01,
    min: 0,
  },
  {
    name: "surchargeAmount",
    label: "Surcharge Amount",
    type: "number",
    required: false,
    placeholder: "Enter surcharge amount",
    step: 0.01,
    min: 0,
    defaultValue: 0,
  },
  {
    name: "discountAmount",
    label: "Discount Amount",
    type: "number",
    required: false,
    placeholder: "Enter discount amount",
    step: 0.01,
    min: 0,
    defaultValue: 0,
  },
  {
    name: "discountDate",
    label: "Discount Date",
    type: "date",
    required: false,
    placeholder: "Select discount date",
  },
  {
    name: "plotFacing",
    label: "Facing Direction",
    type: "select",
    required: false,
    options: [
      { label: "North", value: "N" },
      { label: "South", value: "S" },
      { label: "East", value: "E" },
      { label: "West", value: "W" },
      { label: "Northeast", value: "NE" },
      { label: "Northwest", value: "NW" },
      { label: "Southeast", value: "SE" },
      { label: "Southwest", value: "SW" },
    ],
    placeholder: "Select facing direction",
  },
  {
    name: "plotCornerNo",
    label: "Corner Number",
    type: "number",
    required: false,
    placeholder: "Enter corner number",
    min: 1,
  },
  {
    name: "plotRemarks",
    label: "Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter remarks",
    rows: 3,
  },
  {
    name: "plotLatitude",
    label: "Latitude",
    type: "number",
    required: false,
    placeholder: "Enter latitude",
    step: 0.000001,
    min: -90,
    max: 90,
  },
  {
    name: "plotLongitude",
    label: "Longitude",
    type: "number",
    required: false,
    placeholder: "Enter longitude",
    step: 0.000001,
    min: -180,
    max: 180,
  },
];
