// src/lib/constants/possessionForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { PossessionFormData } from "@/lib/schemas/possession.schema";

export const possessionFormFields: FieldConfig<PossessionFormData>[] = [
  {
    name: "fileId",
    label: "File",
    type: "relationship",
    required: true,
    placeholder: "Select file",
    relationship: {
      endpoint: "/file",
      labelField: "fileNumber",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "plotId",
    label: "Plot",
    type: "relationship",
    required: true,
    placeholder: "Select plot",
    relationship: {
      endpoint: "/plots",
      labelField: "plotNumber",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "possessionInitDate",
    label: "Application Date",
    type: "date",
    required: true,
    placeholder: "Select application date",
  },
  {
    name: "possessionHandoverCSR",
    label: "Handover CSR",
    type: "relationship",
    required: true,
    placeholder: "Select CSR",
    relationship: {
      endpoint: "/users?role=csr",
      labelField: "firstName",
      valueField: "_id",
      searchable: true,
    },
  },
  {
    name: "possessionStatus",
    label: "Status",
    type: "select",
    required: false,
    options: [
      { label: "Requested", value: "requested" },
      { label: "Surveyed", value: "surveyed" },
      { label: "Ready", value: "ready" },
      { label: "Handed Over", value: "handed_over" },
      { label: "Cancelled", value: "cancelled" },
      { label: "On Hold", value: "on_hold" },
    ],
    placeholder: "Select status",
  },
  {
    name: "possessionSurveyPerson",
    label: "Survey Person",
    type: "text",
    required: false,
    placeholder: "Enter survey person name",
  },
  {
    name: "possessionSurveyDate",
    label: "Survey Date",
    type: "date",
    required: false,
    placeholder: "Select survey date",
  },
  {
    name: "possessionCollectorName",
    label: "Collector Name",
    type: "text",
    required: false,
    placeholder: "Enter collector name",
  },
  {
    name: "possessionCollectorNic",
    label: "Collector CNIC",
    type: "text",
    required: false,
    placeholder: "XXXXX-XXXXXXX-X or 13 digits",
  },
  {
    name: "possessionRemarks",
    label: "Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter remarks",
    rows: 3,
  },
  {
    name: "possessionLatitude",
    label: "Latitude",
    type: "number",
    required: false,
    placeholder: "Enter latitude",
    step: 0.000001,
    min: -90,
    max: 90,
  },
  {
    name: "possessionLongitude",
    label: "Longitude",
    type: "number",
    required: false,
    placeholder: "Enter longitude",
    step: 0.000001,
    min: -180,
    max: 180,
  },
];
