// src/lib/constants/projectForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { ProjectFormData } from "@/lib/schemas/project.schema";

export const projectFormFields: FieldConfig<ProjectFormData>[] = [
  {
    name: "projName",
    label: "Project Name",
    type: "text",
    required: true,
    placeholder: "Enter project name",
  },
  {
    name: "projCode",
    label: "Project Code",
    type: "text",
    required: false,
    placeholder: "Will be generated automatically",
  },
  {
    name: "projLocation",
    label: "Location",
    type: "text",
    required: true,
    placeholder: "Enter project location",
  },
  {
    name: "projPrefix",
    label: "Project Prefix",
    type: "text",
    required: true,
    placeholder: "e.g., PRJ, DEV, RES",
  },
  {
    name: "cityId",
    label: "State & City",
    type: "state-city",
    required: true,
    placeholder: "Select state, then city",
  },
  {
    name: "projDescription",
    label: "Description",
    type: "textarea",
    required: false,
    placeholder: "Enter project description",
    rows: 4,
  },
  {
    name: "totalArea",
    label: "Total Area",
    type: "number",
    required: true,
    placeholder: "Enter total area",
    min: 0.01,
    step: 0.01,
  },
  {
    name: "areaUnit",
    label: "Area Unit",
    type: "select",
    required: true,
    options: [
      { label: "Acres", value: "acres" },
      { label: "Hectares", value: "hectares" },
      { label: "Square Feet", value: "sqft" },
      { label: "Square Meters", value: "sqm" },
      { label: "Square Kilometers", value: "km²" },
      { label: "Marla", value: "marla" },
      { label: "Kanal", value: "kanal" },
    ],
    placeholder: "Select area unit",
  },
  {
    name: "launchDate",
    label: "Launch Date",
    type: "date",
    required: true,
    max: new Date(),
  },
  {
    name: "completionDate",
    label: "Completion Date",
    type: "date",
    required: false,
    min: new Date(),
  },
  {
    name: "projStatus",
    label: "Project Status",
    type: "select",
    required: true,
    options: [
      { label: "Planning", value: "planning" },
      { label: "Under Development", value: "under_development" },
      { label: "Completed", value: "completed" },
      { label: "On Hold", value: "on_hold" },
      { label: "Cancelled", value: "cancelled" },
    ],
    defaultValue: "planning",
  },
  {
    name: "projType",
    label: "Project Type",
    type: "select",
    required: true,
    options: [
      { label: "Residential", value: "residential" },
      { label: "Commercial", value: "commercial" },
      { label: "Industrial", value: "industrial" },
      { label: "Mixed Use", value: "mixed_use" },
      { label: "Agricultural", value: "agricultural" },
    ],
    defaultValue: "residential",
  },
  {
    name: "isActive",
    label: "Active Status",
    type: "switch",
    required: false,
    defaultValue: true,
  },
  {
    name: "country",
    label: "Country",
    type: "text",
    required: true,
    defaultValue: "Pakistan",
    placeholder: "Enter country",
  },
  {
    name: "website",
    label: "Website",
    type: "text",
    required: false,
    placeholder: "https://example.com",
  },
  {
    name: "contactEmail",
    label: "Contact Email",
    type: "email",
    required: false,
    placeholder: "contact@example.com",
  },
  {
    name: "contactPhone",
    label: "Contact Phone",
    type: "text",
    required: false,
    placeholder: "+92 300 1234567",
  },
  {
    name: "address",
    label: "Address",
    type: "textarea",
    required: false,
    placeholder: "Enter complete address",
    rows: 2,
  },
  {
    name: "amenities",
    label: "Amenities",
    type: "select",
    required: false,
    options: [
      { label: "Parking", value: "parking" },
      { label: "Security", value: "security" },
      { label: "Water Supply", value: "water_supply" },
      { label: "Electricity", value: "electricity" },
      { label: "Gas", value: "gas" },
      { label: "Drainage", value: "drainage" },
      { label: "Roads", value: "roads" },
      { label: "Parks", value: "parks" },
      { label: "Mosque", value: "mosque" },
      { label: "School", value: "school" },
      { label: "Hospital", value: "hospital" },
      { label: "Shopping Center", value: "shopping_center" },
    ],
    placeholder: "Select amenities",
  },
];
