// src/lib/constants/registryForm.constants.ts
import { FieldConfig } from "@/components/shared/EntityForm/EntityForm";
import { RegistryFormData } from "@/lib/schemas/registry.schema";
import { EntityType } from "@/lib/types/upload.types";

export const registryFormFields: FieldConfig<RegistryFormData>[] = [
  {
    name: "memId",
    label: "Member",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/members",
      labelField: "memName",
      valueField: "_id",
      searchable: true,
      filter: (item: Record<string, unknown>) => !item.isDeleted,
    },
    placeholder: "Select member",
  },
  {
    name: "plotId",
    label: "Plot",
    type: "relationship",
    required: true,
    relationship: {
      endpoint: "/plots",
      labelField: "plotNo",
      valueField: "_id",
      searchable: true,
      filter: (item: Record<string, unknown>) => !item.isDeleted,
    },
    placeholder: "Select plot",
  },
  {
    name: "registryNo",
    label: "Registry No",
    type: "text",
    required: true,
    placeholder: "Enter registry number",
  },
  {
    name: "mutationNo",
    label: "Mutation No",
    type: "text",
    required: true,
    placeholder: "Enter mutation number",
  },
  {
    name: "mutationDate",
    label: "Mutation Date",
    type: "date",
    required: false,
    placeholder: "Select mutation date",
  },
  {
    name: "areaKanal",
    label: "Area (Kanal)",
    type: "number",
    required: false,
    placeholder: "0",
  },
  {
    name: "areaMarla",
    label: "Area (Marla)",
    type: "number",
    required: false,
    placeholder: "0",
  },
  {
    name: "areaSqft",
    label: "Area (Sq ft)",
    type: "number",
    required: false,
    placeholder: "0",
  },
  {
    name: "mozaVillage",
    label: "Moza/Village",
    type: "text",
    required: false,
    placeholder: "Enter moza or village",
  },
  {
    name: "khasraNo",
    label: "Khasra No",
    type: "text",
    required: false,
    placeholder: "Enter khasra number",
  },
  {
    name: "khewatNo",
    label: "Khewat No",
    type: "text",
    required: false,
    placeholder: "Enter khewat number",
  },
  {
    name: "khatoniNo",
    label: "Khatoni No",
    type: "text",
    required: false,
    placeholder: "Enter khatoni number",
  },
  {
    name: "legalOfficeDetails",
    label: "Legal Office Details",
    type: "textarea",
    required: false,
    placeholder: "Enter legal and office details",
    rows: 3,
  },
  {
    name: "subRegistrarName",
    label: "Sub Registrar Name",
    type: "text",
    required: false,
    placeholder: "Enter sub-registrar name",
  },
  {
    name: "agreementDate",
    label: "Agreement Date",
    type: "date",
    required: false,
    placeholder: "Select agreement date",
  },
  {
    name: "stampPaperNo",
    label: "Stamp Paper No",
    type: "text",
    required: false,
    placeholder: "Enter stamp paper number",
  },
  {
    name: "bookNo",
    label: "Book No",
    type: "text",
    required: false,
    placeholder: "Enter book number",
  },
  {
    name: "volumeNo",
    label: "Volume No",
    type: "text",
    required: false,
    placeholder: "Enter volume number",
  },
  {
    name: "documentNo",
    label: "Document No",
    type: "text",
    required: false,
    placeholder: "Enter document number",
  },
  {
    name: "reportNo",
    label: "Report No",
    type: "text",
    required: false,
    placeholder: "Enter report number",
  },
  {
    name: "scanCopyPath",
    label: "Scan Copy",
    type: "image-upload",
    required: false,
    uploadConfig: {
      entityType: EntityType.DOCUMENT,
      entityId: "temp-registry",
      maxSize: 10 * 1024 * 1024,
      aspectRatio: "custom",
    },
    placeholder: "Upload scan copy",
  },
  {
    name: "landOwnerPhoto",
    label: "Land Owner Photo",
    type: "image-upload",
    required: false,
    uploadConfig: {
      entityType: EntityType.DOCUMENT,
      entityId: "temp-registry",
      maxSize: 5 * 1024 * 1024,
      aspectRatio: "square",
    },
    placeholder: "Upload land owner photo",
  },
  {
    name: "remarks",
    label: "Remarks",
    type: "textarea",
    required: false,
    placeholder: "Enter remarks",
    rows: 3,
  },
];
