import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | SocietySphere",
  description:
    "Terms governing use of SocietySphere housing society management software.",
};

const sections = [
  {
    number: 1,
    title: "Acceptance of Terms",
    content: `By accessing or using the SocietySphere platform ("Service"), you acknowledge that you have read, understood, and agree to be bound by these Terms of Service ("Terms"). If you are entering into these Terms on behalf of a housing society, cooperative, or other organization, you represent and warrant that you have the authority to bind such organization to these Terms. If you do not agree to these Terms, you must not access or use the Service.

These Terms constitute a legally binding agreement between you ("User", "you", or "your") and SocietySphere Technologies (Private) Limited ("SocietySphere", "we", "us", or "our"), a company registered under the laws of Pakistan, with its principal office in Islamabad.`,
  },
  {
    number: 2,
    title: "Description of Service",
    content: `SocietySphere is a cloud-based housing society management platform designed specifically for housing societies, cooperative housing schemes, and residential communities in Pakistan. The Service provides comprehensive tools including but not limited to:

\u2022 Plot and property management with ownership tracking and transfer workflows
\u2022 Financial management including billing, dues collection, and accounting
\u2022 Visitor management with QR-code-based digital passes
\u2022 Facility booking and resource management
\u2022 Communication tools for society-wide announcements and member messaging
\u2022 AI-powered insights for financial analytics and predictive management
\u2022 Regulatory compliance features aligned with PLRA and LDA requirements
\u2022 Security management including guard patrol tracking and emergency systems
\u2022 Community engagement features including gamification and event management

The Service is provided on a software-as-a-service (SaaS) basis and is accessible via web browsers and mobile applications. Features and functionality may vary by subscription plan.`,
  },
  {
    number: 3,
    title: "User Accounts",
    content: `To access the Service, you must create an account by providing accurate, complete, and current information including your full name, email address, phone number, and — where required for identity verification — your CNIC number. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.

Each account is for a single individual and may not be shared with or transferred to any other person. You must immediately notify SocietySphere of any unauthorized use of your account or any other breach of security. SocietySphere will not be liable for any loss or damage arising from your failure to comply with these account security requirements.

You agree to keep your account information accurate and up to date. SocietySphere reserves the right to suspend or terminate accounts that contain materially inaccurate or incomplete information.`,
  },
  {
    number: 4,
    title: "Society Administrator Responsibilities",
    content: `If you are designated as an administrator for a housing society on the platform, you bear additional responsibilities:

\u2022 Data Accuracy: You are responsible for ensuring that all society data entered into the platform — including member records, plot information, financial data, and regulatory filings — is accurate, complete, and current.
\u2022 Member Consent: You must obtain appropriate consent from society members before entering their personal data into the platform, in accordance with applicable privacy laws and these Terms.
\u2022 Authorized Usage: You must ensure that all individuals granted access to your society's account on the platform are authorized to access the information available to them, and that role-based permissions are configured appropriately.
\u2022 Regulatory Compliance: You are responsible for ensuring that your use of the platform complies with all applicable local laws and regulations, including but not limited to requirements of the Punjab Land Records Authority (PLRA), Lahore Development Authority (LDA), and any other relevant regulatory bodies.
\u2022 Financial Oversight: You must review and verify all financial reports, billing records, and payment reconciliations generated by the platform before relying on them for official purposes.`,
  },
  {
    number: 5,
    title: "Subscription & Payments",
    content: `SocietySphere offers the following subscription plans:

\u2022 Starter Plan: Free of charge, with limited features suitable for small societies exploring digital management.
\u2022 Professional Plan: PKR 5,000 per month, providing full-featured access for growing societies with up to 500 plots.
\u2022 Enterprise Plan: PKR 15,000 per month, offering advanced features, priority support, custom integrations, and unlimited plots for large-scale societies.

All paid subscriptions are billed monthly in advance. Subscriptions automatically renew at the end of each billing cycle unless cancelled at least 7 days before the renewal date. Prices are exclusive of applicable taxes, which will be added where required by law.

Refund Policy: New subscribers to paid plans are eligible for a full refund within 14 days of their initial subscription purchase if they are not satisfied with the Service. Refund requests must be submitted to billing@societysphere.com within this period.

Payment Methods: We accept payments via JazzCash, Easypaisa, and direct bank transfer. Payment processing is handled by authorized third-party payment processors, and SocietySphere does not store your payment card details.`,
  },
  {
    number: 6,
    title: "Data Ownership",
    content: `Your society's data belongs to your society. SocietySphere does not claim ownership of any data that you or your society members upload, enter, or generate through the Service ("Society Data"). You retain all rights, title, and interest in your Society Data.

You grant SocietySphere a limited, non-exclusive license to process, store, and display your Society Data solely for the purpose of providing and improving the Service. This license terminates when your Society Data is deleted from the platform.

SocietySphere does not sell, rent, or trade your Society Data to third parties for their marketing or commercial purposes. We may use anonymized, aggregated data that cannot be traced back to any individual or society for the purpose of improving our Service, generating industry benchmarks, and conducting research.`,
  },
  {
    number: 7,
    title: "Acceptable Use",
    content: `You agree to use the Service only for its intended purpose of housing society management and in compliance with all applicable laws. You must not:

\u2022 Attempt to gain unauthorized access to the Service, other users' accounts, or the systems and networks connected to the Service
\u2022 Use automated tools to scrape, crawl, or extract data from the Service without prior written authorization
\u2022 Upload or transmit malicious code, viruses, or any material designed to disrupt, damage, or interfere with the operation of the Service
\u2022 Use the Service to harass, abuse, threaten, or intimidate any individual, including society members, staff, or other users
\u2022 Conduct any illegal activities through the platform, including but not limited to fraud, money laundering, or tax evasion
\u2022 Misrepresent your identity or authority when using the Service
\u2022 Reproduce, duplicate, copy, sell, or resell any part of the Service without express written permission from SocietySphere
\u2022 Use the Service to send unsolicited bulk communications (spam) to society members or external parties`,
  },
  {
    number: 8,
    title: "Intellectual Property",
    content: `The Service, including its source code, design, user interface, documentation, logos, trademarks, and all related intellectual property, is owned by SocietySphere Technologies (Private) Limited and is protected by applicable intellectual property laws. Nothing in these Terms grants you any right, title, or interest in the SocietySphere intellectual property except the limited right to use the Service in accordance with these Terms.

Societies retain full ownership of their data, documents, and any content they create using the Service. SocietySphere respects the intellectual property rights of its users and expects its users to respect the intellectual property rights of SocietySphere and third parties.`,
  },
  {
    number: 9,
    title: "Privacy",
    content: `Your privacy is important to us. Our collection, use, and protection of personal data is governed by our Privacy Policy, which is incorporated into these Terms by reference. By using the Service, you consent to the data practices described in our Privacy Policy.

We are committed to providing GDPR-inspired data protection rights to all users, regardless of their geographic location. All data processing occurs within Pakistan, and we maintain robust technical and organizational measures to protect your data. For full details, please review our Privacy Policy.`,
  },
  {
    number: 10,
    title: "Service Availability",
    content: `SocietySphere targets 99.9% uptime availability for the Service, measured on a monthly basis. We will make commercially reasonable efforts to minimize downtime and ensure reliable access to the Service.

Scheduled maintenance will be performed during off-peak hours (typically between 2:00 AM and 5:00 AM PKT) with at least 48 hours advance notice to administrators. Emergency maintenance required to address security vulnerabilities or critical system issues may be performed without advance notice.

SocietySphere shall not be liable for any downtime, service interruptions, or performance degradation caused by force majeure events, including but not limited to natural disasters, acts of government, internet service provider failures, power outages, cyberattacks, or other events beyond our reasonable control.`,
  },
  {
    number: 11,
    title: "Limitation of Liability",
    content: `To the maximum extent permitted by applicable law, SocietySphere and its officers, directors, employees, agents, and affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including but not limited to loss of profits, data, or business opportunities, arising out of or related to your use of the Service, regardless of the theory of liability.

In no event shall SocietySphere's total cumulative liability to you for all claims arising out of or related to these Terms or the Service exceed the total amount of fees paid by you to SocietySphere in the twelve (12) months immediately preceding the event giving rise to the claim.

This limitation of liability applies regardless of whether the damages are based on warranty, contract, tort, strict liability, or any other legal theory, and regardless of whether SocietySphere has been advised of the possibility of such damages.`,
  },
  {
    number: 12,
    title: "Termination",
    content: `Either party may terminate these Terms at any time by providing written notice. If you wish to terminate your account, you may do so through the account settings page or by contacting support@societysphere.com.

Upon termination, your right to access the Service will cease immediately. However, you will have a 30-day grace period following termination during which you may export your Society Data in standard formats (JSON, CSV, PDF). After this 30-day period, your Society Data will be permanently deleted from our active systems, though it may persist in encrypted backups for up to 90 days in accordance with our data retention policy.

SocietySphere reserves the right to immediately suspend or terminate your account without prior notice if you violate these Terms, engage in fraudulent activity, or use the Service in a manner that threatens the security, integrity, or availability of the platform for other users.`,
  },
  {
    number: 13,
    title: "Dispute Resolution",
    content: `These Terms shall be governed by and construed in accordance with the laws of the Islamic Republic of Pakistan, without regard to its conflict of law provisions.

In the event of any dispute, controversy, or claim arising out of or relating to these Terms or the Service, the parties agree to first attempt resolution through good-faith mediation for a period of thirty (30) days. The mediation shall be conducted by a mutually agreed-upon mediator in Islamabad.

If the dispute cannot be resolved through mediation within thirty (30) days, either party may submit the dispute to the exclusive jurisdiction of the competent courts in Islamabad, Pakistan. Both parties consent to the personal jurisdiction of such courts and waive any objection to the convenience of such forum.`,
  },
  {
    number: 14,
    title: "Changes to Terms",
    content: `SocietySphere reserves the right to modify these Terms at any time. For material changes, we will provide at least thirty (30) days advance notice via email to the address associated with your account and through a prominent notice on the platform.

Your continued use of the Service after the effective date of any modification constitutes your acceptance of the modified Terms. If you do not agree with the modified Terms, you must stop using the Service and terminate your account before the effective date of the changes.

Non-material changes, such as typographical corrections or clarifications that do not alter the substance of the Terms, may be made without advance notice.`,
  },
  {
    number: 15,
    title: "Contact Information",
    content: `If you have any questions, concerns, or feedback regarding these Terms of Service, please contact us at:

SocietySphere Technologies (Private) Limited
Legal Department
Blue Area, Jinnah Avenue
Islamabad, 44000, Pakistan

Email: legal@societysphere.com
Phone: +92-51-XXX-XXXX

For general support inquiries, please contact support@societysphere.com.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      {/* Navbar */}
      <nav className="border-b border-slate-200 bg-white">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4">
          <Link
            href="/"
            className="text-xl font-bold tracking-tight text-emerald-600"
          >
            SocietySphere
          </Link>
          <div className="flex items-center gap-3">
            <Link
              href="/login"
              className="rounded-lg px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-100"
            >
              Login
            </Link>
            <Link
              href="/signup"
              className="rounded-lg bg-emerald-600 px-4 py-2 text-sm font-medium text-white transition hover:bg-emerald-700"
            >
              Sign Up
            </Link>
          </div>
        </div>
      </nav>

      {/* Content */}
      <div className="mx-auto max-w-4xl px-6 py-12">
        <Link
          href="/"
          className="mb-8 inline-flex items-center gap-1 text-sm text-emerald-600 transition hover:text-emerald-700 hover:underline"
        >
          &larr; Back to Home
        </Link>

        <article className="mt-4">
          <h1 className="font-serif text-4xl font-bold tracking-tight text-slate-900">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-slate-500">
            Last updated: June 18, 2026
          </p>

          <div className="mt-10 space-y-10">
            {sections.map((section) => (
              <section key={section.number}>
                <h2 className="flex items-baseline gap-3 border-l-4 border-emerald-500 pl-4 font-serif text-xl font-semibold text-slate-900">
                  <span className="text-emerald-600">{section.number}.</span>
                  {section.title}
                </h2>
                <div className="mt-4 space-y-4 pl-4">
                  {section.content.split("\n\n").map((paragraph, i) => (
                    <p
                      key={i}
                      className="text-base leading-relaxed text-slate-700"
                    >
                      {paragraph}
                    </p>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </article>
      </div>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-slate-50">
        <div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-6 py-8 sm:flex-row">
          <p className="text-sm text-slate-500">
            &copy; 2026 SocietySphere. All rights reserved.
          </p>
          <div className="flex gap-6">
            <Link
              href="/terms"
              className="text-sm text-slate-600 hover:text-emerald-600"
            >
              Terms
            </Link>
            <Link
              href="/privacy"
              className="text-sm text-slate-600 hover:text-emerald-600"
            >
              Privacy
            </Link>
            <Link
              href="/cookies"
              className="text-sm text-slate-600 hover:text-emerald-600"
            >
              Cookies
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
